<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "custom_rest"
 *
 * Auto generated by Extension Builder 2014-05-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Custom REST extensions',
	'description' => 'Customized examples for the REST extension',
	'category' => 'plugin',
	'author' => 'Daniel Corn',
	'author_email' => 'info@cundd.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);